### ISSUE TITLE
DLL Not Found Issue

### ISSUE THREAD

**Issue by syeddanishdev** [labstreaminglayer/PicoNeo2Eye#3]
In Scene Scripts

EventController.cs
EventLSLOutlet.cs

DllNotFoundException: lsl
LSL.liblsl+StreamInfo..ctor (System.String name, System.String type, System.Int32 channel_count, System.Double nominal_srate, LSL.liblsl+channel_format_t channel_format, System.String source_id) (at Assets/Plugins/LSL.cs:156)
EventLSLOutlet.Start () (at Assets/Scripts/EventLSLOutlet.cs:29)

DllNotFoundException: lsl
LSL.liblsl.local_clock () (at Assets/Plugins/LSL.cs:115)
EventLSLOutlet+<WriteAfterImageIsRendered>d__10.MoveNext () (at Assets/Scripts/EventLSLOutlet.cs:48)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:187)

**Comment by cboulay** [comment]
You're not actually using a Pico Neo 2 Eye so I'm closing this issue.
